use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum ModelId {
    // OpenAI
    Gpt4o,
    Gpt4oMini,
    Gpt4,
    Gpt4Turbo,
    Gpt3_5Turbo,
    O1,
    O1Mini,
    O3,
    O3Mini,
    O4,
    O4Mini,
    // Anthropic
    Claude3_5Sonnet,
    Claude3Opus,
    Claude3Haiku,
    Claude3_5Haiku,
    Claude4,
    Claude4Opus,
    // Google
    Gemini2_0Flash,
    Gemini2_0Pro,
    Gemini2_5Flash,
    Gemini2_5Pro,
    Gemini1_5Pro,
    Gemini1_5Flash,
    // xAI
    Grok2,
    Grok2Vision,
    Grok3,
    Grok3Mini,
    // Meta
    Llama3_70b,
    Llama3_8b,
    Llama3_1_70b,
    Llama3_1_8b,
    Llama3_1_405b,
    Llama3_2_90b,
    Llama3_2_11b,
    Llama3_2_3b,
    Llama3_2_1b,
    Llama4,
    Llama4Scout,
    Llama4Maverick,
    // Mistral
    MistralLarge,
    MistralMedium,
    MistralSmall,
    Mistral7b,
    Mixtral8x22b,
    Mixtral8x7b,
    MistralCodestral,
    MistralCodestralMamba,
    MistralMathstral,
    // Qwen
    Qwen2_5,
    Qwen2_5Coder,
    Qwen2_5Math,
    Qwen2_5VL,
    Qwen3,
    Qwen3Coder,
    Qwen3MoE,
    QwenMax,
    QwenPlus,
    QwenTurbo,
    // DeepSeek
    DeepseekV3,
    DeepseekV3Base,
    DeepseekR1,
    DeepseekR1DistillLlama,
    DeepseekR1DistillQwen,
    DeepseekCoderV2,
    DeepseekMath,
    // Zhipu / GLM
    Glm4,
    Glm4Plus,
    Glm4Air,
    Glm4Flash,
    Glm4Code,
    Glm4v,
    Glm4vPlus,
    // Moonshot / Kimi
    KimiK1_5,
    KimiK2,
    KimiK2_5,
    KimiVL,
    KimiVL2,
    // Arcee
    ArceeAgent,
    ArceeBlender,
    ArceeFusion,
    ArceeNova,
    ArceeOrion,
    // Hermes
    Hermes3,
    Hermes3Pro,
    Hermes3Small,
    // Nous
    NousHermes2,
    NousHermes2Mixtral,
    // Cohere
    CommandR,
    CommandRPlus,
    CommandLight,
    CommandR7b,
    // AI21
    Jamba,
    JambaMini,
    JambaUltra,
    // Microsoft
    Phi4,
    Phi4Mini,
    Phi4Multimodal,
    // Alibaba
    TongyiQianwenMax,
    TongyiQianwenPlus,
    TongyiQianwenTurbo,
    // 01.AI
    YiLarge,
    YiMedium,
    YiSmall,
    YiVision,
    // Stability
    StableLm,
    StableCode,
    // Other
    Gemma2,
    Gemma2_9b,
    Gemma2_27b,
    Gemma3,
    Gemma3Mini,
    Nemotron,
    NemotronMini,
    Codestral,
    CodestralMamba,
    Aya,
    AyaExpanse,
    // 2026 frontier
    Gpt5,
    Gpt5Mini,
    Gemini3_0Flash,
    Gemini3_0Pro,
    Claude5,
    Grok4,
    Llama5,
    Qwen4,
    DeepseekV4,
    Custom(String),
}

impl std::fmt::Display for ModelId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ModelId::Gpt4o => write!(f, "gpt-4o"),
            ModelId::Gpt4oMini => write!(f, "gpt-4o-mini"),
            ModelId::Gpt4 => write!(f, "gpt-4"),
            ModelId::Gpt4Turbo => write!(f, "gpt-4-turbo"),
            ModelId::Gpt3_5Turbo => write!(f, "gpt-3.5-turbo"),
            ModelId::O1 => write!(f, "o1"),
            ModelId::O1Mini => write!(f, "o1-mini"),
            ModelId::O3 => write!(f, "o3"),
            ModelId::O3Mini => write!(f, "o3-mini"),
            ModelId::O4 => write!(f, "o4"),
            ModelId::O4Mini => write!(f, "o4-mini"),
            ModelId::Claude3_5Sonnet => write!(f, "claude-3-5-sonnet"),
            ModelId::Claude3Opus => write!(f, "claude-3-opus"),
            ModelId::Claude3Haiku => write!(f, "claude-3-haiku"),
            ModelId::Claude3_5Haiku => write!(f, "claude-3-5-haiku"),
            ModelId::Claude4 => write!(f, "claude-4"),
            ModelId::Claude4Opus => write!(f, "claude-4-opus"),
            ModelId::Gemini2_0Flash => write!(f, "gemini-2.0-flash"),
            ModelId::Gemini2_0Pro => write!(f, "gemini-2.0-pro"),
            ModelId::Gemini2_5Flash => write!(f, "gemini-2.5-flash"),
            ModelId::Gemini2_5Pro => write!(f, "gemini-2.5-pro"),
            ModelId::Gemini1_5Pro => write!(f, "gemini-1.5-pro"),
            ModelId::Gemini1_5Flash => write!(f, "gemini-1.5-flash"),
            ModelId::Grok2 => write!(f, "grok-2"),
            ModelId::Grok2Vision => write!(f, "grok-2-vision"),
            ModelId::Grok3 => write!(f, "grok-3"),
            ModelId::Grok3Mini => write!(f, "grok-3-mini"),
            ModelId::Llama3_70b => write!(f, "llama-3-70b"),
            ModelId::Llama3_8b => write!(f, "llama-3-8b"),
            ModelId::Llama3_1_70b => write!(f, "llama-3.1-70b"),
            ModelId::Llama3_1_8b => write!(f, "llama-3.1-8b"),
            ModelId::Llama3_1_405b => write!(f, "llama-3.1-405b"),
            ModelId::Llama3_2_90b => write!(f, "llama-3.2-90b"),
            ModelId::Llama3_2_11b => write!(f, "llama-3.2-11b"),
            ModelId::Llama3_2_3b => write!(f, "llama-3.2-3b"),
            ModelId::Llama3_2_1b => write!(f, "llama-3.2-1b"),
            ModelId::Llama4 => write!(f, "llama-4"),
            ModelId::Llama4Scout => write!(f, "llama-4-scout"),
            ModelId::Llama4Maverick => write!(f, "llama-4-maverick"),
            ModelId::MistralLarge => write!(f, "mistral-large"),
            ModelId::MistralMedium => write!(f, "mistral-medium"),
            ModelId::MistralSmall => write!(f, "mistral-small"),
            ModelId::Mistral7b => write!(f, "mistral-7b"),
            ModelId::Mixtral8x22b => write!(f, "mixtral-8x22b"),
            ModelId::Mixtral8x7b => write!(f, "mixtral-8x7b"),
            ModelId::MistralCodestral => write!(f, "codestral"),
            ModelId::MistralCodestralMamba => write!(f, "codestral-mamba"),
            ModelId::MistralMathstral => write!(f, "mathstral"),
            ModelId::Qwen2_5 => write!(f, "qwen-2.5"),
            ModelId::Qwen2_5Coder => write!(f, "qwen-2.5-coder"),
            ModelId::Qwen2_5Math => write!(f, "qwen-2.5-math"),
            ModelId::Qwen2_5VL => write!(f, "qwen-2.5-vl"),
            ModelId::Qwen3 => write!(f, "qwen-3"),
            ModelId::Qwen3Coder => write!(f, "qwen-3-coder"),
            ModelId::Qwen3MoE => write!(f, "qwen-3-moe"),
            ModelId::QwenMax => write!(f, "qwen-max"),
            ModelId::QwenPlus => write!(f, "qwen-plus"),
            ModelId::QwenTurbo => write!(f, "qwen-turbo"),
            ModelId::DeepseekV3 => write!(f, "deepseek-v3"),
            ModelId::DeepseekV3Base => write!(f, "deepseek-v3-base"),
            ModelId::DeepseekR1 => write!(f, "deepseek-r1"),
            ModelId::DeepseekR1DistillLlama => write!(f, "deepseek-r1-distill-llama"),
            ModelId::DeepseekR1DistillQwen => write!(f, "deepseek-r1-distill-qwen"),
            ModelId::DeepseekCoderV2 => write!(f, "deepseek-coder-v2"),
            ModelId::DeepseekMath => write!(f, "deepseek-math"),
            ModelId::Glm4 => write!(f, "glm-4"),
            ModelId::Glm4Plus => write!(f, "glm-4-plus"),
            ModelId::Glm4Air => write!(f, "glm-4-air"),
            ModelId::Glm4Flash => write!(f, "glm-4-flash"),
            ModelId::Glm4Code => write!(f, "glm-4-code"),
            ModelId::Glm4v => write!(f, "glm-4v"),
            ModelId::Glm4vPlus => write!(f, "glm-4v-plus"),
            ModelId::KimiK1_5 => write!(f, "kimi-k1.5"),
            ModelId::KimiK2 => write!(f, "kimi-k2"),
            ModelId::KimiK2_5 => write!(f, "kimi-k2.5"),
            ModelId::KimiVL => write!(f, "kimi-vl"),
            ModelId::KimiVL2 => write!(f, "kimi-vl2"),
            ModelId::ArceeAgent => write!(f, "arcee-agent"),
            ModelId::ArceeBlender => write!(f, "arcee-blender"),
            ModelId::ArceeFusion => write!(f, "arcee-fusion"),
            ModelId::ArceeNova => write!(f, "arcee-nova"),
            ModelId::ArceeOrion => write!(f, "arcee-orion"),
            ModelId::Hermes3 => write!(f, "hermes-3"),
            ModelId::Hermes3Pro => write!(f, "hermes-3-pro"),
            ModelId::Hermes3Small => write!(f, "hermes-3-small"),
            ModelId::NousHermes2 => write!(f, "nous-hermes-2"),
            ModelId::NousHermes2Mixtral => write!(f, "nous-hermes-2-mixtral"),
            ModelId::CommandR => write!(f, "command-r"),
            ModelId::CommandRPlus => write!(f, "command-r-plus"),
            ModelId::CommandLight => write!(f, "command-light"),
            ModelId::CommandR7b => write!(f, "command-r7b"),
            ModelId::Jamba => write!(f, "jamba"),
            ModelId::JambaMini => write!(f, "jamba-mini"),
            ModelId::JambaUltra => write!(f, "jamba-ultra"),
            ModelId::Phi4 => write!(f, "phi-4"),
            ModelId::Phi4Mini => write!(f, "phi-4-mini"),
            ModelId::Phi4Multimodal => write!(f, "phi-4-multimodal"),
            ModelId::TongyiQianwenMax => write!(f, "qwen-max"),
            ModelId::TongyiQianwenPlus => write!(f, "qwen-plus"),
            ModelId::TongyiQianwenTurbo => write!(f, "qwen-turbo"),
            ModelId::YiLarge => write!(f, "yi-large"),
            ModelId::YiMedium => write!(f, "yi-medium"),
            ModelId::YiSmall => write!(f, "yi-small"),
            ModelId::YiVision => write!(f, "yi-vision"),
            ModelId::StableLm => write!(f, "stable-lm"),
            ModelId::StableCode => write!(f, "stable-code"),
            ModelId::Gemma2 => write!(f, "gemma-2"),
            ModelId::Gemma2_9b => write!(f, "gemma-2-9b"),
            ModelId::Gemma2_27b => write!(f, "gemma-2-27b"),
            ModelId::Gemma3 => write!(f, "gemma-3"),
            ModelId::Gemma3Mini => write!(f, "gemma-3-mini"),
            ModelId::Nemotron => write!(f, "nemotron"),
            ModelId::NemotronMini => write!(f, "nemotron-mini"),
            ModelId::Codestral => write!(f, "codestral"),
            ModelId::CodestralMamba => write!(f, "codestral-mamba"),
            ModelId::Aya => write!(f, "aya"),
            ModelId::AyaExpanse => write!(f, "aya-expanse"),
            ModelId::Gpt5 => write!(f, "gpt-5"),
            ModelId::Gpt5Mini => write!(f, "gpt-5-mini"),
            ModelId::Gemini3_0Flash => write!(f, "gemini-3.0-flash"),
            ModelId::Gemini3_0Pro => write!(f, "gemini-3.0-pro"),
            ModelId::Claude5 => write!(f, "claude-5"),
            ModelId::Grok4 => write!(f, "grok-4"),
            ModelId::Llama5 => write!(f, "llama-5"),
            ModelId::Qwen4 => write!(f, "qwen-4"),
            ModelId::DeepseekV4 => write!(f, "deepseek-v4"),
            ModelId::Custom(name) => write!(f, "{}", name),
        }
    }
}
